spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sqlanalyzer
    username: postgres
    password: DemoSVB@2025
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
